name: Deploy

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          retention-days: 5

  E2E-Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - name: Install
        run: npm ci

      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60

  Publish:
    runs-on: ubuntu-latest
    needs: [Build, E2E-Tests]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          environment-url: https://zettca.github.io/pacex/
          environment: production
